### ISSUE TITLE
[BUG]加载解压的扩展后，新标签页没变化

### ISSUE THREAD

**Issue by hsingll** [mayneyao/InfoCard#1]
![Snipaste-14-11-56](https://user-images.githubusercontent.com/26346635/54510481-675c6880-4988-11e9-82da-1baf2fa046df.png)
仅标题栏有变化

**Comment by mayneyao** [comment]
我折腾了下，发布到chrome商店了。你现在可以直接从商店安装：https://chrome.google.com/webstore/detail/infocard/joelaehdgkmbjapdnpcfindkdkjplaka/

因为只是demo性质的，所以没有做完善的兼容测试。

如果还是有问题，麻烦贴一下控制台报错，谢谢你的反馈😄
