### ISSUE TITLE
[建议]能不能加上目录，可跳转到其他章节阅读

### ISSUE THREAD

**Issue by hsingll** [mayneyao/InfoCard#2]
碰上感兴趣的书籍想看一下全部的，就只能跳转到github里看了，还是插件的风格比较好看

**Comment by mayneyao** [comment]
抱歉，最近琐事较多没来得及回复。
目录这个功能我想过，单用前端不是很好做。举个例子，很多开源图书会用 chapter001.md 而不是第一章的标题作为文件名。要获取到目录，必须遍历文件，解析出文件中的h1。这样开销比较大（github api 请求限制），所以没法做成实时的，只有做成缓存。

又因为开源图书会更新，所以文件的sha值是变化的，没法做到一次缓存始终有效。而且各个开源图书的文件组织风格不一样。每种情况都适配到，工作量较大。

可以考虑手工维护 json文件，将章节名称与目录文件名一一映射。类似gitbook的做法（需要在图书源的维护上下功夫

或许加个后端会比较合适...

emmmm，实现思路比较多，我暂时没想到比较好的做法，先放在todo里面吧。 当然也欢迎 PR 😃
